"""database o'zgardi

Revision ID: 150f1df95a2d
Revises: d2e1736d7d9d
Create Date: 2023-12-15 10:39:51.318428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150f1df95a2d'
down_revision = 'd2e1736d7d9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
