"""review image adde

Revision ID: 1caf7f732fee
Revises: d94c3cffee4b
Create Date: 2024-01-08 16:42:29.708145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1caf7f732fee'
down_revision = 'd94c3cffee4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('star', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'star')
    # ### end Alembic commands ###
