"""cash added to user default 1000

Revision ID: 223dc7dc14dc
Revises: 16b611db84fc
Create Date: 2023-12-22 15:31:33.669368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223dc7dc14dc'
down_revision = '16b611db84fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cash', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cash')
    # ### end Alembic commands ###
