"""edited subcategory table

Revision ID: 4123f29d5baa
Revises: 44eedfdb165e
Create Date: 2023-12-11 11:39:17.558561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4123f29d5baa'
down_revision = '44eedfdb165e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniqNS', 'subcategory', ['name', 'subcategory'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniqNS', 'subcategory', type_='unique')
    # ### end Alembic commands ###
