"""bugs fixed

Revision ID: 4375df6bdff1
Revises: ca5c1e162e74
Create Date: 2023-12-11 17:20:24.755427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4375df6bdff1'
down_revision = 'ca5c1e162e74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('product', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'subcategory', ['subcategory_id'], ['id'])
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_category_id_fkey', 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'subcategory_id')
    op.drop_column('product', 'created_at')
    # ### end Alembic commands ###
