"""hash changed

Revision ID: 4db1f15e6c79
Revises: 5d26d19f3929
Create Date: 2023-12-20 17:31:56.682801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db1f15e6c79'
down_revision = '5d26d19f3929'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file', ['hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='unique')
    # ### end Alembic commands ###
