"""changes for user_like

Revision ID: 55a085d3a1b1
Revises: b695e7d09826
Create Date: 2024-02-07 14:51:30.150249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a085d3a1b1'
down_revision = 'b695e7d09826'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_like', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_like', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_like', type_='foreignkey')
    op.drop_column('user_like', 'product_id')
    # ### end Alembic commands ###
