"""hash added to file model

Revision ID: 5d26d19f3929
Revises: cd4bc4f2052b
Create Date: 2023-12-20 17:21:31.644381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d26d19f3929'
down_revision = 'cd4bc4f2052b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'hash')
    # ### end Alembic commands ###
