"""BankCard model created

Revision ID: 8d704312bf4c
Revises: a89f00a78d5c
Create Date: 2023-12-25 16:21:29.703112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d704312bf4c'
down_revision = 'a89f00a78d5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=True),
    sa.Column('card_expiration', sa.String(length=4), nullable=True),
    sa.Column('card_cvc', sa.String(length=3), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_card')
    # ### end Alembic commands ###
