"""name changed to code in color table

Revision ID: a89f00a78d5c
Revises: 0518d7cfa92a
Create Date: 2023-12-25 10:48:01.252413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89f00a78d5c'
down_revision = '0518d7cfa92a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('code', sa.String(length=7), nullable=True))
    op.drop_column('color', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('color', 'code')
    # ### end Alembic commands ###
