"""database o'zgardi

Revision ID: aeaf9f5ff32c
Revises: 150f1df95a2d
Create Date: 2023-12-15 10:47:17.851143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeaf9f5ff32c'
down_revision = '150f1df95a2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
