"""discount field added

Revision ID: ca5c1e162e74
Revises: 4123f29d5baa
Create Date: 2023-12-11 16:05:13.974769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5c1e162e74'
down_revision = '4123f29d5baa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file', 'product', ['product_id'], ['id'])
    op.add_column('product', sa.Column('discount_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'discount_percent')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'product_id')
    # ### end Alembic commands ###
