"""database o'zgardi

Revision ID: d2e1736d7d9d
Revises: b7966913f7f7
Create Date: 2023-12-15 10:27:27.368836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e1736d7d9d'
down_revision = 'b7966913f7f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joined_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'joined_at')
    # ### end Alembic commands ###
