"""size model changed

Revision ID: dabbb456452d
Revises: b7966913f7f7
Create Date: 2023-12-15 17:30:06.599094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabbb456452d'
down_revision = 'b7966913f7f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('size', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'size', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'size', type_='foreignkey')
    op.drop_column('size', 'category_id')
    # ### end Alembic commands ###
